level: info  
tg:
  token: 5475270624:AAERBBvCnwUH6jPabNDaI4V5H0bi5CRh28c
ipstack:
  key: ca402f37b8a60c07d301ed7487d4441e
rabbit:
  host: localhost
  port: 5672
  username: guest
  password: guest
  consumer:
    ipstack: "tg-cons"
    buffer: 10
  producer:
    name:  "tg-prod"
event:
  worker: 3 
postgresqldb:
  username: postgres
  password: Loken
  host: localhost
  port: 5432
  dbname: devdb
